export const POST_VALUE_REQUEST = 'POST_VALUE_REQUEST';
export const POST_VALUE_SUCCESS = 'POST_VALUE_SUCCESS';
export const POST_VALUE_FAILURE = 'POST_VALUE_FAILURE';
export const GET_VALUE_REQUEST = 'GET_VALUE_REQUEST';
export const GET_VALUE_SUCCESS = 'GET_VALUE_SUCCESS';
export const GET_VALUE_FAILURE = 'GET_VALUE_FAILURE';